name: javaee-app build and deploy to remote wildfly

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2

      - name: Set up JDK 11
        uses: actions/setup-java@1
        with:
          java-version: 11

      - name: Build with Maven
        id: mvn_build
        run: |
          mvn --batch-mode clean install wildfly:deploy -Dwildfly.hostname=${{ secrets.WILDFLY_HOSTNAME }} \
          -Dwildfly.username=${{ secrets.WILDFLY_LOGIN_ADMIN }} \
          -Dwildfly.password=${{ secrets.WILDFLY_ADMIN_PASSWORD }}